action: cross_validate
cv_state: 1234
data_args:
  alpha: 0.01
  features:
  - contratto
  - ore_settimana
  - dimensioni_azienda
  - settore
  - qualifica
  - titolo_studio
  - tipo_laurea
  - tipo_diploma
  - regione
  - ampiezza_comune
  - anni_da_primo_lavoro
  - anni_da_lavoro_corrente
  - anni_da_edu
  - anni_contributi
  - n_esp_lavorative
experiment: hparam_search
model: ProbNN
model_args:
  batch_size: 256
  distr: normal
  dropout: 0.3
  embedding_size: 16
  epochs: 100
  lr: 0.0003
  num_nodes:
  - 32
n_splits: 5
random_state: 1234
run_name: probnn_002
store_artifacts: false
tags: {}
